# Generated by Django 5.1 on 2024-08-12 08:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("kind", models.CharField(default="Dog", max_length=25)),
                ("age", models.IntegerField()),
                ("owner_first_name", models.CharField(max_length=50)),
                ("owner_last_name", models.CharField(max_length=50)),
                (
                    "owner_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="RU"
                    ),
                ),
                ("special_signs", models.CharField(max_length=100)),
            ],
        ),
    ]
